name: Release for Linux

on:
   workflow_call:
      inputs:
         tag:
            description: Tag
            required: true
            type: string
         arch:
            description: Architecture
            required: true
            type: string

jobs:
   release-linux:
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout
            uses: actions/checkout@v4

         -  name: Setup Go
            uses: actions/setup-go@v5
            with:
               go-version-file: "go.mod"

         -  name: Build
            shell: bash
            run: |
               set -e
               mkdir dist
               cd build/linux
               chmod +x build.sh
               ./build.sh ${{ inputs.tag }} ${{ inputs.arch }}
               mv spicetify ../../dist/spicetify-${{ inputs.tag }}-linux-${{ inputs.arch }}

         -  name: Release
            uses: softprops/action-gh-release@v2
            with:
               files: "dist/*"
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
