name: Release

on:
   release:
      types: [published]

jobs:
   tag:
      name: Release
      runs-on: ubuntu-latest
      if: startsWith(github.ref, 'refs/tags/v3')
      outputs:
         tag: ${{ steps.set-env.outputs.tag }}
      steps:
      -  id: set-env
         name: Set Env
         run: echo "tag=${GITHUB_REF#refs/*/v}" >> "$GITHUB_OUTPUT"

   release-linux:
      uses: ./.github/workflows/release-linux.yml
      needs: tag
      strategy:
         matrix:
            arch: [amd64, arm64]
      with:
         tag: ${{ needs.tag.outputs.tag }}
         arch: ${{ matrix.arch }}
      secrets:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   release-macos:
      uses: ./.github/workflows/release-macos.yml
      needs: tag
      with:
         tag: ${{ needs.tag.outputs.tag }}
      secrets:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   release-windows:
      uses: ./.github/workflows/release-windows.yml
      needs: tag
      strategy:
         matrix:
            arch: [386, amd64, arm64]
      with:
         tag: ${{ needs.tag.outputs.tag }}
         arch: ${{ matrix.arch }}
      secrets:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
