name: Release

on:
   release:
      types: [published]

jobs:
   setup:
      name: Release
      runs-on: ubuntu-latest
      if: startsWith(github.ref, 'refs/tags/v3')
      outputs:
         tag: ${{ steps.set-env.outputs.tag }}
      steps:
      -  id: set-env
         name: Set Env
         run: echo "tag=${GITHUB_REF#refs/*/v}" >> "$GITHUB_OUTPUT"

   build-linux:
      uses: ./.github/workflows/build-linux.yml
      permissions:
         contents: write
         id-token: write
         attestations: write
      needs: setup
      strategy:
         matrix:
            arch: [amd64, arm64]
      with:
         tag: ${{ needs.setup.outputs.tag }}
         arch: ${{ matrix.arch }}

   build-macos:
      uses: ./.github/workflows/build-macos.yml
      permissions:
         contents: write
         id-token: write
         attestations: write
      needs: setup
      with:
         tag: ${{ needs.setup.outputs.tag }}

   build-windows:
      uses: ./.github/workflows/build-windows.yml
      permissions:
         contents: write
         id-token: write
         attestations: write
      needs: setup
      strategy:
         matrix:
            arch: [386, amd64, arm64]
      with:
         tag: ${{ needs.setup.outputs.tag }}
         arch: ${{ matrix.arch }}

   release:
      runs-on: ubuntu-latest
      needs: [setup, build-linux, build-macos, build-windows]
      permissions:
         id-token: write
         attestations: write
      steps:
         -  name: Download artifacts
            uses: actions/download-artifact@v4
            with:
               path: dist
               merge-multiple: true

         -  name: Add version
            shell: bash
            run: |
               set -e
               cd dist
               for file in spicetify-*; do
                  mv "$file" "spicetify-${{ needs.setup.outputs.tag }}${file#spicetify}"
               done

         -  name: Attest
            uses: actions/attest-build-provenance@v1
            with:
               subject-path: "dist/*"

         -  name: Release
            uses: softprops/action-gh-release@v2
            with:
               files: "dist/*"
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
